name: Generate Live Threat Map

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate_threat_map:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate Threat Map SVG
        uses: RavinduRathnayaka/LiveThreatMap-dashboard@main
        with:
          SHODAN_API_KEY: ${{ secrets.SHODAN_API_KEY }}
